// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTEWvrhu80i9ow0ag7_HqE8CBsnRSr7ic',
    appId: '1:59765864426:web:7362e3f828e2e4116e6493',
    messagingSenderId: '59765864426',
    projectId: 'flutter-prep-2b40f',
    authDomain: 'flutter-prep-2b40f.firebaseapp.com',
    databaseURL: 'https://flutter-prep-2b40f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2b40f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv_y88ZL5vLWy6a0uaIIqJ8GVxd6FH720',
    appId: '1:59765864426:android:18aa53109bb0a0416e6493',
    messagingSenderId: '59765864426',
    projectId: 'flutter-prep-2b40f',
    databaseURL: 'https://flutter-prep-2b40f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2b40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4jDSDQ0O8f57foi7vqwxNkpLAy8d9pvo',
    appId: '1:59765864426:ios:4ddafca1b9202c196e6493',
    messagingSenderId: '59765864426',
    projectId: 'flutter-prep-2b40f',
    databaseURL: 'https://flutter-prep-2b40f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2b40f.firebasestorage.app',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4jDSDQ0O8f57foi7vqwxNkpLAy8d9pvo',
    appId: '1:59765864426:ios:4ddafca1b9202c196e6493',
    messagingSenderId: '59765864426',
    projectId: 'flutter-prep-2b40f',
    databaseURL: 'https://flutter-prep-2b40f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2b40f.firebasestorage.app',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTEWvrhu80i9ow0ag7_HqE8CBsnRSr7ic',
    appId: '1:59765864426:web:37c572bdefe133bd6e6493',
    messagingSenderId: '59765864426',
    projectId: 'flutter-prep-2b40f',
    authDomain: 'flutter-prep-2b40f.firebaseapp.com',
    databaseURL: 'https://flutter-prep-2b40f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-2b40f.firebasestorage.app',
  );
}
